/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.VolunteerRole;

import models.Contribution.Contribution;
import models.Contributor.Contributor;
import models.AppSystem;
import models.Person.Person;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import ui.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author naina
 */
public class ApproveRejectIndContributionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApproveRejectIndContributionJPanel
     */
    private JPanel userProcessContainer;
    private AppSystem system;
    private Person user;

    public ApproveRejectIndContributionJPanel(JPanel userProcessContainer, Person user, AppSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.user = user;

        populateIndividualContribution();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIndividualContribution = new javax.swing.JTable();
        btnBack1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 244, 246));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        jLabel1.setText("Manage Individual Contribution");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        btnApprove.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(67, 0, 163));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        btnReject.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnReject.setForeground(new java.awt.Color(67, 0, 163));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 160, -1));

        tblIndividualContribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Item", "Quantity", "Expiry Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblIndividualContribution);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 614, 150));

        btnBack1.setBackground(new java.awt.Color(255, 255, 255));
        btnBack1.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnBack1.setText("Back");
        btnBack1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectRow = tblIndividualContribution.getSelectedRow();
        Contribution contribution = (Contribution) tblIndividualContribution.getValueAt(selectRow, 0);
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            if (contribution.getStatus().equals("Approved")) {
                JOptionPane.showMessageDialog(null, "Contribution already approved", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } 
            else if (contribution.getStatus().equals("Rejcted")) {
                JOptionPane.showMessageDialog(null, "Contribution already rejcted", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
            else {
                JOptionPane.showMessageDialog(null, "Contribution Approved");
                contribution.setStatus("Approved");
            }
        }
        populateIndividualContribution();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        int selectRow = tblIndividualContribution.getSelectedRow();
        Contribution contribution = (Contribution) tblIndividualContribution.getValueAt(selectRow, 0);
        if (selectRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            if (contribution.getStatus().equals("Rejected")) {
                JOptionPane.showMessageDialog(null, "Contribution already rejected", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } 
            else if(contribution.getStatus().equals("Approved")) {
                JOptionPane.showMessageDialog(null, "Contribution already Approved", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } 
            else {
                contribution.setStatus("Rejected");
                JOptionPane.showMessageDialog(null, "Contribution Rejected");
            }
        }
        populateIndividualContribution();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnReject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIndividualContribution;
    // End of variables declaration//GEN-END:variables

    private void populateIndividualContribution() {

        DefaultTableModel model = (DefaultTableModel) tblIndividualContribution.getModel();

        model.setRowCount(0);

        for (Contributor admin : system.getContributorDirectory().getContributorList()) {

            if ("models.Role.VolunteerRole".equals(user.getRole().getClass().getName())) {
                for (Contribution contribution : admin.getContribution()) {
                    Object[] row = new Object[5];
                    row[0] = contribution;
                    row[1] = contribution.getItem();
                    row[2] = contribution.getQuantity();
                    row[3] = contribution.getExpiryDate();
                    row[4] = contribution.getStatus();
                    model.addRow(row);
                }

            }
        }

    }
}
