/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DeliveryAdminRole;

import models.Contribution.Contribution;
import models.Contributor.Contributor;
import models.AppSystem;
import models.Store.Store;
import models.Person.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author naina
 */
public class DeliveryAdminAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryAdminJPanel
     */
    private JPanel userProcessContainer;
    private AppSystem system;
    Person user;

    public DeliveryAdminAreaJPanel(JPanel userProcessContainer, Person account, AppSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = account;
        this.system = system;

        populateContributionTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStoreContribution = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnMap = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStoreContribution.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Store Name", "Item", "Quantity", "Expiry Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblStoreContribution);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 640, 130));

        btnUpdate.setBackground(new java.awt.Color(67, 0, 163));
        btnUpdate.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Details");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 180, 40));

        btnMap.setBackground(new java.awt.Color(255, 255, 255));
        btnMap.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnMap.setForeground(new java.awt.Color(67, 0, 163));
        btnMap.setText("View Locations");
        btnMap.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 0, 163)));
        btnMap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMapActionPerformed(evt);
            }
        });
        add(btnMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 180, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Delivery Admin Portal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblStoreContribution.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Contribution contribution = (Contribution) tblStoreContribution.getValueAt(selectedRow, 0);
            if (contribution.getStatus().equals("New Request")) {
                JOptionPane.showMessageDialog(null, "Waiting for approval from Volunteer", "Warning", JOptionPane.WARNING_MESSAGE);
            }
//else if (contribution.getStatus().equals("Assigned to Agency")) {
//                JOptionPane.showMessageDialog(null, "Already Assigned ", "Warning", JOptionPane.WARNING_MESSAGE);
//            } 
                else {
                UpdateDetailsJPanel udjp = new UpdateDetailsJPanel(userProcessContainer, user, contribution, system);
                userProcessContainer.add("UpdateDetailsJPanel", udjp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMapActionPerformed
        // TODO add your handling code here:
        MapJPanel mvjp = new MapJPanel(userProcessContainer, system);
        userProcessContainer.add("Manage Volunteers", mvjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnMapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMap;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStoreContribution;
    // End of variables declaration//GEN-END:variables

    private void populateContributionTable() {
        DefaultTableModel model = (DefaultTableModel) tblStoreContribution.getModel();

        model.setRowCount(0);

        for (Store admin : system.getStoreDirectory().getStoreDirectory()) {

            if ("models.Role.DeliveryAdminRole".equals(user.getRole().getClass().getName())) {
                for (Contribution contribution : admin.getContribution()) {
                    Object[] row = new Object[5];
                    row[0] = contribution;
                    row[1] = contribution.getItem();
                    row[2] = contribution.getQuantity();
                    row[3] = contribution.getExpiryDate();
                    row[4] = contribution.getStatus();
                    model.addRow(row);
                }

            }
        }
        for (Contributor admin : system.getContributorDirectory().getContributorList()) {
            if ("models.Role.DeliveryAdminRole".equals(user.getRole().getClass().getName())) {
                for (Contribution contribution : admin.getContribution()) {
                    Object[] row = new Object[5];
                    row[0] = contribution;
                    row[1] = contribution.getItem();
                    row[2] = contribution.getQuantity();
                    row[3] = contribution.getExpiryDate();
                    row[4] = contribution.getStatus();
                    model.addRow(row);
                }

            }
        }
    }
}
