/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.ContributorRole;

import models.AppSystem;
import models.Person.Person;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author naina
 */
public class ContributorAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ContributorRoleJPanel
     */
    
    private JPanel userProcessContainer;
    private AppSystem ecosystem;
    private Person userAccount;
    public ContributorAreaJPanel(JPanel userProcessContainer, Person account, AppSystem ecosystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        
        jLabel1.setText("Welcome "+account.getUsername());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddContribution = new javax.swing.JButton();
        btnViewContribution = new javax.swing.JButton();
        viewProfile = new javax.swing.JButton();

        setBackground(new java.awt.Color(243, 244, 246));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Hello There Contributor!");

        btnAddContribution.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnAddContribution.setForeground(new java.awt.Color(67, 0, 163));
        btnAddContribution.setText("Add Contribution");
        btnAddContribution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddContributionActionPerformed(evt);
            }
        });

        btnViewContribution.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnViewContribution.setForeground(new java.awt.Color(67, 0, 163));
        btnViewContribution.setText("View Contribution History");
        btnViewContribution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewContribution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewContributionActionPerformed(evt);
            }
        });

        viewProfile.setText("View Profile");
        viewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(viewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddContribution, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(246, Short.MAX_VALUE)
                    .addComponent(btnViewContribution)
                    .addGap(175, 175, 175)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(viewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(btnAddContribution, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(248, Short.MAX_VALUE)
                    .addComponent(btnViewContribution, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(122, 122, 122)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddContributionActionPerformed
        // TODO add your handling code here:
        AddContributionJPanel acjp = new AddContributionJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("Add Contribution", acjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddContributionActionPerformed

    private void btnViewContributionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewContributionActionPerformed
        ViewContributionJPanel vcjp = new ViewContributionJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("View Contribution History", vcjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewContributionActionPerformed

    private void viewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewProfileActionPerformed
        ViewContributorProfileJPanel vvpjp = new ViewContributorProfileJPanel(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("View Profile", vvpjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddContribution;
    private javax.swing.JButton btnViewContribution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewProfile;
    // End of variables declaration//GEN-END:variables
}
